### ISSUE TITLE
Web Service unavailable

### ISSUE THREAD

**Issue by Alekos92** [NICTA/t3as-snomedct-service#1]
Hello. 

I know this project hasn't been updated in a long time, and I don't know if you track issues at this point. 
However, you claim that there exists a web service of the SNOMED CT entity recognizer that users can try. The provided page http://snomedct.t3as.org/ does not work, and I wonder if there exists a workaround. 

Thank you.

**Comment by neilbacon** [comment]
Hi, yes, as you've noted this project is no longer maintained or hosted. Sorry about that. I hope you can find something to suit your needs or perhaps use this as inspiration for your own solution.
